### ISSUE TITLE
It doesn't work at all

### ISSUE THREAD

**Issue by greatkeke** [msound/localmongo#1]
I have cloned your repository, and run `docker-compose up`, it ran successfully. But it doesn't created replica set at all.

**Comment by msound** [comment]
@kexxxfeng Can you confirm if you are running `master` branch or `4.0` branch?

**Comment by greatkeke** [comment]
@msound It's too long to remember which one I have tried. I almost forgot the error detail. I'm sorry to disturb you, close it now, thx:)
