### ISSUE TITLE
Do I need to run rs.initiate?

### ISSUE THREAD

**Issue by devarthurribeiro** [msound/localmongo#2]
According to the documentation it is necessary:

https://docs.mongodb.com/manual/tutorial/deploy-replica-set/

**Comment by msound** [comment]
@devarthurribeiro  You are right. For some time, my 4.0 setup worked fine without this step, I am unable to explain why. But I do concede that `rs.initiate()` is required. I have updated my repo to reflect your suggestion, as well as updated the branches for `4.0` and `4.2`. Thanks for raising this issue.
